products = [
  {
    '_id': '1',
    'name': 'Nhẫn cưới Kim cương Vàng 18K PNJ Chung Đôi 00611-00604',
    'image': '/images/nhan-cuoi-kim-cuong-pnj-chung-doi-vang-18k-ya36226-ya36227.png',
    'description': 'Giữa hai tâm hồn đồng điệu với nhau thì đám cưới sẽ là cái kết tuyệt đẹp cho cả hai và nhẫn cưới chính là yếu tố không thể thiếu trong ngày trọng đại này. Hiện nay, nhẫn cưới được thiết kế biến hóa theo xu hướng thời trang với những điểm nhấn đá quý nổi bật và sang trong, tuy nhiên vẫn giữ được vẻ đẹp truyền thống cũng như ý nghĩa vốn có của nó.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 12087000,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Nhẫn cưới Kim cương Vàng 18K PNJ Chung Đôi 00705-00701',
    'image': '/images/gnd1ya71522.500-gnd1ya71523.500-nhan-cuoi-kim-cuong-pnj-chung-doi-vang-18k-01.png',
    'description':
      'Thu hút bởi kiểu dáng tinh xảo, hài hoà đến từng đường nét, nhẫn cưới "Chung Đôi" với thiết kế nhẫn nam và nhẫn nữ đồng nhất, mang đến ấn tượng về sự đồng cảm, sẻ chia. ',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 10038000,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Nhẫn cưới Vàng 18K PNJ Sánh Duyên 00032-00031',
    'image': '/images/gnd1ya71522.500-gnd1ya71523.500-nhan-cuoi-kim-cuong-pnj-chung-doi-vang-18k-01.png',
    'description':
      'Việc chọn nhẫn cưới là bước vô cùng quan trọng và tốn nhiều tâm tư của các cặp đôi trong ngày trọng đại. Phải lựa chọn như thế nào để có thể dung hòa giữa vẻ đẹp dịu dàng của người phụ nữ và nét nam tính, mạnh mẽ của cánh mày râu luôn là vấn đề nan giải. Hiểu được vấn đề này, PNJ mang đến các mẫu nhẫn cưới tinh tế, giúp cho cặp đôi có nhiều sự lựa chọn.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 12609000,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Nhẫn cưới Kim cương Vàng 18K PNJ Tình Hồng 00004-00007',
    'image': '/images/nhan-cuoi-kim-cuong-pnj-tinh-hong-vang-18k-ha82599-82600.png',
    'description':
      'Nếu nhẫn đính hôn chỉ dành cho nữ thì nhẫn cưới dành cho cả 2 người. Từ xa xưa, nhẫn cưới có thiết kế tròn trơn thì ngày nay, nhẫn cưới được thiết kế cầu kỳ, đính thêm các loại đá quý hoặc khắc tên,… Đặc biệt hơn, PNJ mang đến những mẫu nhẫn là sự kết hợp giữa chất liệu vàng hồng hoặc trắng hồng,… làm tô điểm nét phá cách và hiện đại cho sản phẩm.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 16758000,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Nhẫn cưới Kim cương Vàng 18K PNJ Chung Đôi 00847-00843',
    'image': '/images/nhan-cuoi-kim-cuong-nam-pnj-chung-doi-vang-18k-ya75490-75491.png',
    'description':
      'Nhẫn cưới kim cương luôn là một trong những lựa chọn hàng đầu của các cặp vợ chồng vì vẻ đẹp và ý nghĩa mà kim cương mang lại. Kim cương là đá quý cứng nhất, vì thế nó đại diện cho sự vĩnh cửu trong tình yêu. Bản chất bền bỉ và sức mạnh phi thường của kim cương như một mối liên hệ thiết thực giữa tình yêu bền chặt của các cặp vợ chồng.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 12594000,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Nhẫn cưới Vàng 18K PNJ Sánh Duyên 00379-00378',
    'image': '/images/gndrya87212.000-gndrya87213.000-nhan-cuoi-pnj-sanh-duyen-vang-18k.png',
    'description':
      'Nhẫn Cưới Sánh Duyên mang phong cách thiết kế ngẫu hứng với những đường nét phá cách đơn giản, thanh thoát nhưng không kém phần tinh tế, nhẫn cưới " Sánh Duyên " tượng trưng cho sự hòa quyện, gắn kết không thể tách rời.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 11465000,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '7',
    'name': 'Dây chuyền Vàng Ý 18K PNJ đính đá 0000X000035',
    'image': '/images/gbdrya71539.014-bong-tai-cuoi-pnj-vu-khuc-tinh-yeu-vang-24k-0001.png',
    'description':
      'Những món trang sức ngọc trai đến từ thương hiệu PNJ luôn mang trong mình vẻ đẹp tinh tế. Với vẻ đẹp trong sáng, dịu dàng đầy nữ tính, đôi bông tai cưới PNJ vàng trắng 14K đính ngọc trai hiện đang được rất nhiều quý cô ưa chuộng.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 7615000,
    'countInStock': 0,
    'rating': 4.8,
    'numReviews': 10,
  },
  {
    '_id': '8',
    'name': 'Bông tai Vàng trắng 10K đính đá ECZ PNJ XMXMW001370',
    'image': '/images/gbxmxmw001370-bong-tai-vang-trang-10k-dinh-da-ecz-swarovski-pnj-01.png',
    'description': '',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 4894000,
    'countInStock': 0,
    'rating': 4.5,
    'numReviews': 8,
  },
  {
    '_id': '9',
    'name': 'Bông tai Vàng 10K đính đá Suncut PNJ ZTXMY000524',
    'image': '/images/gbztxmy000524-bong-tai-vang-10k-dinh-da-suncut-swarovski-pnj.png',
    'description':
      'Cùng đón nhận vẻ đẹp tinh tế và độc đáo của đôi bông tai Sunflower đến từ thương hiệu trang sức PNJ. Được thiết kế với các chi tiết cánh hoa màu vàng óng ả kết hợp viên đá Suncut Swarovski với 86 giác cắt tinh tế, tạo nên đôi bông tai hoàn hảo, giúp các quý cô trông tự tin và rạng rỡ, tô điểm cho vẻ đẹp của nàng bởi nàng chính là ánh mặt trời ấm áp, tỏa nắng xung quanh.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 5025000,
    'countInStock': 0,
    'rating': 4.7,
    'numReviews': 15,
  },
  {
    '_id': '10',
    'name': 'Bông tai Vàng trắng Ý 18K đính đá CZ PNJ XMXMW000451',
    'image': '/images/gbxmxmw000451-bong-tai-pnj-vang-trang-y-18k-dinh-da-cz.png',
    'description':
      'Không ngừng sáng tạo cũng như nắm bắt xu thế thời trang trong thiết kế, PNJ luôn đem đến những mẫu trang sức vàng có vẻ đẹp hoàn mỹ và thanh lịch. Không chỉ mang vẻ đẹp trẻ trung, quyến rũ của chất liệu vàng trắng Ý 18K, đôi hoa tai còn sở hữu nét tinh tế và sáng bóng của đá CZ, đã làm say đắm biết bao cô nàng yêu thích trang sức.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 3952000,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 10,
  },
  {
    '_id': '11',
    'name': 'Bông tai Vàng trắng 14K đính đá Topaz PNJ TPXMW000032',
    'image': '/images/gbdrwa58088.601-bong-tai-pnj-vang-trang-14k-dinh-da-topaz.png',
    'description':
      'Bông tai, chất liệu vàng trắng 14K, gắn 2 viên Topaz vuông 7.0 ly+ đá CZ: 12 viên 1.0 ly.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 7076000,
    'countInStock': 0,
    'rating': 4.6,
    'numReviews': 14,
  },
  {
    '_id': '12',
    'name': 'Bông tai Vàng trắng Ý 18K PNJ 0000W000044',
    'image': '/images/gb0000w000044-bong-tai-vang-trang-y-pnj-01.png',
    'description':
      'Món phụ kiện không thể thiếu của các cô gái chính là đôi bông tai, nó không chỉ tô điểm nét đẹp dịu dàng mà còn điểm nhấn riêng của gương mặt của họ. Vì vậy PNJ giới thiệu với khách hàng nhiều kiểu thiết kế bông mang phong cách thời trang của Ý và đôi khuyên tai được chế tác từ chất liệu vàng trắng 18K  này sẽ món nữ trang thích hợp cho bạn.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 2993000,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '13',
    'name': 'Bông tai Vàng 18K đính đá Ruby PNJ RBXMY000028',
    'image': '/images/gbdrya71605.600-bong-tai-pnj-vang-18k-dinh-da-ruby.png',
    'description':
      'Bông tai, chất liệu vàng 18K, gắn 2 viên Ruby tròn 6.0 ly + 34 viên đá CZ 1.25 ly. Trọng lượng vàng tương ứng giá bán: 0.72 chỉ.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 10205000,
    'countInStock': 0,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '14',
    'name': 'Bông tai Vàng 18K đính đá CZ PNJ XM00Y000085',
    'image': '/images/gbdrya57702.102-bong-tai-pnj-vang-18k-dinh-da-cz-01.png',
    'description':
      'Xu hướng thời trang hiện nay vẫn không ngừng sáng tạo và phát triển. Đã có rất nhiều kiểu khuyên tai đến và đi nhưng vẫn chưa có kiểu nào có thể “soán ngôi” được ngôi vị hàng đầu của đôi bông tai đính đá nổi bật. Có thể nói rằng, bông tai đính đá chính là item cần-phải-có trong bộ sưu tập trang sức của phái đẹp.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 4079000,
    'countInStock': 0,
    'rating': 4.8,
    'numReviews': 16,
  },
  {
    '_id': '15',
    'name': 'Bông tai Vàng 18K đính đá CZ PNJ XM00Y000093',
    'image': '/images/gbdrya73657.102-bong-tai-pnj-vang-18k-dinh-da-cz.png',
    'description':
      'Đổi mới phong cách của mình với sự giúp sức của những món trang sức vàng sang trọng và tinh tế của PNJ, chắc chắn các quý cô sẽ trông thật mới mẻ và nổi bật. Đôi bông tai vàng với thiết kế nhỏ xinh không chỉ là nữ trang nhấn nhá cho vẻ đẹp mà còn khẳng định sự sang trọng và tinh tế cho nàng.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 3502000,
    'countInStock': 0,
    'rating': 4.6,
    'numReviews': 20,
  },
  {
    '_id': '16',
    'name': 'Vòng tay cưới Vàng 24K đính đá PNJ 0000Y06000B621',
    'image': '/images/gv0000y060002-vong-tay-cuoi-vang-24k-pnj.png',
    'description':
      'Tròn với những họa tiết rồng phượng uốn lượn đó chính là những từ miêu tả về các sản phẩm vòng tay cưới. Ngày nay xã hội phát triển cùng xu hướng thời trang không ngừng sáng tạo, PNJ mang đến những trang sức cưới với nhiều kiểu dáng mới lạ nhưng vẫn giữ nét truyền thống, tạo nên vẻ ngoài trẻ trung, sang trọng và thời thượng.',
    'brand': 'PNJ',
    'category': 'Jewelry',
    'price': 11763000,
    'countInStock': 0,
    'rating': 4.5,
    'numReviews': 8,
  },
]

